### ISSUE TITLE
support non numeric fields in pie plot grouping field

### ISSUE THREAD

**Issue by Mi-Kbs-gis** [ghtmtt/DataPlotly#119]
To make pie plots related some categories, please support grouping by non numeric fields.

**Comment by ghtmtt** [comment]
Could you please provide a plot template of what the plot should look like?

**Comment by Mi-Kbs-gis** [comment]
![grafik](https://user-images.githubusercontent.com/25895003/57512375-bdf07e00-730b-11e9-8551-4f26eee5b946.png)

**Comment by ghtmtt** [comment]
I suppose the standard solution is not what you are looking for:

![image](https://user-images.githubusercontent.com/2884884/58000405-fb59c600-7ad8-11e9-9856-40b672d79b18.png)


the grouping field works already with not numerical field (`Profo` is used in the example). Should dig into plotly API to see if the count of object is available instead of the %

**Comment by Mi-Kbs-gis** [comment]
That's it. Thank you.
