### ISSUE TITLE
Can't create polar charts

### ISSUE THREAD

**Issue by gvanhavre** [ghtmtt/DataPlotly#218]
**Describe the bug**
Can't produce scatterpolar plots with the plugin. Using plotly in RStudio, I can produce them with the same data.

Stack Trace:

> **AttributeError: module 'plotly.graph_objs' has no attribute 'Scatterpolar'** 
> Traceback (most recent call last):
>   File "/home/harkonnen/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/gui/plot_settings_widget.py", line 1166, in create_plot
>     plot_factory = self.create_plot_factory()
>   File "/home/harkonnen/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/gui/plot_settings_widget.py", line 1123, in create_plot_factory
>     plot_factory = PlotFactory(settings, visible_region=visible_region)
>   File "/home/harkonnen/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/core/plot_factory.py", line 113, in __init__
>     self.rebuild()
>   File "/home/harkonnen/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/core/plot_factory.py", line 398, in rebuild
>     self.trace = self._build_trace()
>   File "/home/harkonnen/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/core/plot_factory.py", line 415, in _build_trace
>     return PlotFactory.PLOT_TYPES[self.settings.plot_type].create_trace(self.settings)
>   File "/home/harkonnen/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/core/plot_types/polar.py", line 36, in create_trace
>     return [graph_objs.Scatterpolar(
> AttributeError: module 'plotly.graph_objs' has no attribute 'Scatterpolar'

Version de Python : 3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0] 
Version de QGIS : 3.10.5-A Coruña A Coruña, 984615fe1e 

**Screenshots**
![Capture du 2020-04-22 11-12-48](https://user-images.githubusercontent.com/1637612/79992801-5d117580-848a-11ea-8ba8-96eed03a4aef.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 18
 - QGIS release: 3.10
 - DataPlotly release 3.6

**Comment by gvanhavre** [comment]
Tried with simpler data (without decimals), but got the same problem.

**Comment by barja8** [comment]
Hi @gvanhavre is possible that you can share you data?, because in my case I've tried to replicate this problem with other data and my result is different; at moment I have QGIS 3.12.2 in Xubuntu 19.10, in this link [**Qgisproject**](https://github.com/barja8/Friends/raw/master/gvanhavre%20/Bug_QGIS.zip) I attach the repoducible project.
<img src= 'https://github.com/barja8/Friends/blob/master/gvanhavre%20/Bug_QGIS/qgis_features.png' width='100'> <img src= https://github.com/barja8/Friends/blob/master/gvanhavre%20/Bug_QGIS/Bug.png width='100'>

**Comment by gvanhavre** [comment]
Hello @barja8, thank for sharing a reproducible project. I loaded it and got the same error (exact same text from Stack Trace as before).

![Capture du 2020-04-22 16-08-30](https://user-images.githubusercontent.com/1637612/80023190-8bf01180-84b3-11ea-90cc-b223f026f517.png)

From your data, I could make a plot on R (only with switched axes), so I guess plotly is working on the system:

![newplot](https://user-images.githubusercontent.com/1637612/80023641-3831f800-84b4-11ea-9b93-4525948497a6.png)

**Comment by barja8** [comment]
@gvanhavre  From my point of view I think that you should reinstall QGIS o maybe Dataplotly because I'm working with the same [**project**](https://github.com/barja8/Friends/raw/master/gvanhavre%20/QGIS_Bug.zip) in **QGIS 3.10.X** with the **DataPlolty 3.6** and the result are the next: 
<img src='https://github.com/barja8/Friends/blob/master/gvanhavre%20/Bug_QGIS/Img-Windows/windows_bug01.png?raw=true'>
<img src='https://github.com/barja8/Friends/blob/master/gvanhavre%20/Bug_QGIS/Img-Windows/windows_bug02.png?raw=true'>

**Comment by ghtmtt** [comment]
same here. Loaded the project and created the plot. No errors:

![immagine](https://user-images.githubusercontent.com/2884884/80072286-50525780-8546-11ea-83cb-45f58c26a952.png)

Given that you are using Linux I guess you installed plotly by yourself. Could you please try the following?

* open a python console in QGIS
* copy and paste `import plotly`
* copy and paste `plotly.__version__`

Which version of plotly is installed on your machine?

**Comment by gvanhavre** [comment]
```
>>> plotly.__version__
'2.2.3'
>>> 
```

**Comment by ghtmtt** [comment]
ok you are using then a very old plotly version. Just upgrade it with Officially (in OSGEO4W) the supported version of plotly is 3.6 but also using a version > 4 the plugin is working.

**Comment by gvanhavre** [comment]
That's it! Had to install pip3 and update setuptools, but it worked. Now the plot displays just fine with both the reproducible example from @barja8 and my own data. 
Thanks a lot!
